9.15. Помощь друга
htmlacademy-univer-javascript-1/2433767-kekstagram-4 pull request #12
Opened 2023-12-19 14:57 UTC by bnzhkkk

2023-12-19 18:39 UTC, MaksimovG requested changes

2023-12-19 18:39 UTC, MaksimovG commented on js/effects.js
> +export const onFilterButtonChange = (evt) => {
и зачем она экспортируется

2023-12-19 18:39 UTC, MaksimovG commented on js/effects.js
> +const effectValue = document.querySelector('.effect-level__value');
в начале кода идут константы

2023-12-19 18:39 UTC, MaksimovG commented on js/effects.js
> +const Effects = {
Effect - без множественного числа

2023-12-19 18:39 UTC, MaksimovG commented on js/effects.js
> +  chrome: {
CHROME

2023-12-19 18:39 UTC, MaksimovG commented on js/effects.js
> +  sepia: {
SEPIA и тд

2023-12-19 18:39 UTC, MaksimovG commented on js/effects.js
> +  const evtHandler = evt.target.value;
просто target = 

Handler используется для других случаев

2023-12-19 18:39 UTC, MaksimovG commented on js/effects.js
> +    slider.noUiSlider.updateOptions(Effects[evtHandler].options);
так как мы переименуем ключи в объекте Effect то тут понадобится .toUpperCase()

2023-12-19 20:35 UTC, bnzhkkk commented on js/effects.js
> +export const onFilterButtonChange = (evt) => {
в form.js используется

2023-12-20 16:39 UTC, MaksimovG requested changes

2023-12-20 16:39 UTC, MaksimovG commented on js/effects.js
> +
Почему переменные идут выше констант

2023-12-20 16:39 UTC, MaksimovG commented on js/effects.js
> +export const onFilterButtonChange = (evt) => {
это был риторический вопрос, каждую лекцию говорил - обработчики из модуля не экспортируем, если вы экспортируете обработчик - это уже не модуль. Это просто файл с функциями.  Так что делайте это нормальным модулем или переносите все в form.js

2023-12-21 17:03 UTC, merged